### ISSUE TITLE
Maven dependencies Air Gab environment

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#10]
Good morning,

We're trying to set up a i2 Analyze in docker on a air gab network. I still have some questions:

1. Are all the Maven dependencies included in the Minimal Toolkit (/pre-reqs/i2analyze/toolkit/i2-tools/jars). As far as I can see this is the complete list mentioned in https://i2group.github.io/analyze-containers/versions/2.7.0/content/reference%20architecture/external_dependencies.html?q=dependency.

2. Now a reference is add to a generic page to setup a Docker registry and Maven repo. It would be very helpful if a step-by-step plan was added as to what needs to be adjusted in the i2 Analyze containers to set up this 'internal' Docker registry and Maven repo's.

**Comment by Anthony-Johnson-i2** [comment]
Hi Steven

I have  reached out to dev for clarification on this but do not have a response for you yet.

Cheers

**Comment by Matt-Hadfield-i2** [comment]
Hi @sdorresteijn88 ,

After you have set up your Docker registry and Maven repository, they should be picked up automatically by analyze-containers when you run the `create-dev-environment` command.

If you have already got an analyze-containers environment running, you will need to run `manage-environment -t update` and then `create-dev-environment`.

If you have any extensions, they will use the Maven repository when they are rebuilt. You can do this by running `manage-environment -t extensions`.

Thanks

**Comment by sdorresteijn88** [comment]
Hi @Matt-Hadfield-i2 

Thanks a lot!
