### ISSUE TITLE
Differences between Dev en Pre-prod environment

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#11]
Good morning,

According to the documentation, https://i2group.github.io/analyze-containers/versions/2.4.0/content/getting_started.html, it's possible to set up a Dev environment and a Pre-production environment.

What are the biggest (most important) differences between those setups?

**Comment by Matt-Hadfield-i2** [comment]
Hi @sdorresteijn88 ,

The dev environment is designed to develop i2 Analyze configuration and can be used for small deployments and demos.

The pre-production example deployment is designed to show you how you can deploy the analyze-containers images manually using the client functions and writing your own deployment scripts or using a cloud provider such as AWS.

Thanks,
Matt
