### ISSUE TITLE
OpenShift compatibility

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#12]
Good afternoon,

Is it possible to run the i2 Analyze containers in a OpenShift environment?

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 
I had a chat with the dev team on this and the answer is that images might be portable, but  we have not tested this so do not have a definite yes or no for you.

**Comment by sdorresteijn88** [comment]
Hi @Anthony-Johnson-i2 
Thanks a lot, good to know that it might be possible.
