### ISSUE TITLE
Analyze Containers Prometheus and Grafana credentials

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-containers#14]
I'm confused over how to access the Prometheus and Grafana web clients on i2 Analyze Containers.

Under Images and Containers and the individual sections for Grafana and Prometheus I can see that there are environment variables for the usernames and passwords.

I can also see that there's a client script function to see if all env vars are set (check_env_vars_are_set) and another to retrieve secrets (get_secret). 

But here I get unstuck. When VSCode has ~analzye-containers open it doesn't have access to the utils/client_functions.sh script - permission denied. VSCode is running under an identity of vscode. Drats - do I need to remember the root user again? Painful as I always forget with wsl.

Would be useful to update docs to clarify how to access the monitoring capabilities in the included containers.

**Comment by Matt-Hadfield-i2** [comment]
Hi @bohdanszymanik ,

Are you using a configuration development environment deployment, if you are the documentation here describes how to access both web clients: https://i2group.github.io/analyze-containers/content/develop_monitoring.html

The images and containers docs are more about the concept of deploying those images and containers manually in another environment such as AWS. However you should be able to access them in a similar way once deployed.

Thanks,

**Comment by bohdanszymanik** [comment]
Doh! That's perfect. Thanks:)
