### ISSUE TITLE
Some services on the i2 Analyze server are unavailable.

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#17]
Good morning,

We have a demo environment at Digital Ocean. After I did the upgrade to i2 Analyze 4.2.2 and analyze-containers v 2.7.0 I didn't get it working again.

1. After the upgrade I got the message 'Error: The leader Liberty was not elected in time.' when I deployed the config.
2. I did a clean deploy, but without success. After this I restarted the server.
3. After this I deployed the config again, and it seems to be successful.
4. But when I tried to use i2 Analyze via Chrome I received the error that some services are unavailable.

What can I do to fix this?

![image](https://github.com/i2group/analyze/assets/52672945/2a4e9e45-c990-46e5-9aef-5e56e410d2c9)
![image](https://github.com/i2group/analyze/assets/52672945/d0be4ade-4450-41cc-9720-8764810b73bb)
![image](https://github.com/i2group/analyze/assets/52672945/a129b214-396a-4bf6-895b-2cdc5b728eb2)

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 
I am closing this issue off as it relates to multiple things, most of which are resolved.

If you find you still have a problem with Postgres at the latest release ( as we discussed you trying when you had time) please feel free to open a new issue for that.

Cheers
