### ISSUE TITLE
Connectors doesn't start 

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#18]
**Describe the bug**
After the update to i2 Analyze 4.4.3 and container version 2.8.0 I have a lot of trouble getting the connectors of the type 'i2connect-server' running. 

The error below I get in the container logs of the connector.
```
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/.npm/_cacache/tmp/a0042286
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:0 "/opt/app-root/src/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

Before the update my local setup was working fine, is this something related with the update?

**To Reproduce**
Last week I ran 'manage-environment -t connectors' and 'deploy -c {{configName}} -t clean' and I created new packages of the connectors after I updated the connectors with 'npm update'. Finally I got it working, but now I try to start the environment again and I have the same issue again.

**Expected behavior**
I expect that when I have the environment running it will run the next time again (when I don't make changes).

**Hardware and Software information**
Fill in the following information:

- OS: [e.g. Mac, Windows] Windows
- Version: [e.g. v2.0.0] 2.8.0
- i2 Analyze version: [e.g. 4.3.4] 4.4.3
- Environment type: [e.g. pre-prod, config-dev] dev
- Deployment pattern: [e.g. istore, i2c, cstore, i2c_istore, i2c_cstore, schema_dev] i2c_istore

**Comment by Ariana-Hlavaty-i2** [comment]
@sdorresteijn88 we haven't made changes to the connectors for this release so shouldn't be related. It seems like your file permissions are being changed in between runs. 
How are you making changes to the connector code? Are you running a separate VSCode window and copy/paste or is it a tgz built somewhere else?

**Comment by sdorresteijn88** [comment]
@Ariana-Hlavaty-i2 thanks for your quick reply! Good to know that there where no changes in the connector part.

I use to make the changes in a separate VSCode window where I create the tgz build. I copy the tgz build to connector folder of my i2 Analyze setup.

**Comment by Ariana-Hlavaty-i2** [comment]
It could be that the npm you are using to build the connector is an older version with the permission problem. Upgrade to node 18 and npm 10 if you haven't already.

Another cause could be an old docker cache. Please run `manage-environment -t connectors` and redeploy.

**Comment by sdorresteijn88** [comment]
@Ariana-Hlavaty-i2 I'll check tomorrow the Node and NPM version. 

I tried already the 'manage-environment -t connectors', but without success.

**Comment by sdorresteijn88** [comment]
@Ariana-Hlavaty-i2 I have npm version 10.3.0 and Node version 20.11.0

**Comment by Ariana-Hlavaty-i2** [comment]
@sdorresteijn88 can you check the permissions of all the connector files before doing npm pack and ensure they aren't owned by root?
Also check that any dependencies you are using are compatible with node 18 and upwards.

**Comment by Ariana-Hlavaty-i2** [comment]
Great to know it is working now. The warning about npm version will go away when the base ubi image we use from red hat gets updated. You won't need to update analyze-containers.

**Comment by sdorresteijn88** [comment]
@Ariana-Hlavaty-i2 I didn't update anything and now the issue is back again. It was working for a couple of days and when I tried to start it this morning I got the same error.
