### ISSUE TITLE
Documentation enhancement request: extension development under i2 Analyze Containers

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-containers#19]
### Background 
The extension development documentation in https://i2group.github.io/analyze-containers/content/develop_extensions.html is difficult to reconcile with the examples in the i2 Analyze SDK eg the audit logging example (https://github.com/i2group/analyze/blob/master/documentation/java-api/Configuring-the-audit-logging-to-database-example-project.md), specifically the name of the class implementing the AuditLogger referred to in the SDK as being in ApolloServerSettingsMandatory.properties.

The trick I realised with the i2 Containers docs is that the build scripts use pre-reqs/templates properties files. So I just needed to set the name of the class implementing AuditLogger there and run a new deply. Anyhow, this isn't fully described in the i2 Analyze Containers documentation for building an extension. And actually, I spent a bit of time wondering where I should put CSVAudit.properties - that was a quick case of trial and error.

### Request
Provide a bit more detail in the i2 Analyze Containers extensions documentation to make the audit logging example easier to set up and clearer to understand how the i2 Analyze Containers environment changes the dev process versus i2 Analyze.

**Comment by Anthony-Johnson-i2** [comment]
Thank you @bohdanszymanik for taking the time to raise this here.

@Matt-Hadfield-i2  and/or @Jon-Hill-i2 can we get your views on this please it sounds like a useful request.

Cheers

**Comment by Matt-Hadfield-i2** [comment]
Hi @bohdanszymanik,

We have the following bit of documentation:

You can now start developing your extension. For examples on i2 Analyze extensions, check the examples in i2 Analyze Developer Essentials.

1.     Copy the contents of `src/main` folder of the extension into the `i2a-extensions/<artifact_id>/src/main` directory.
2.     Add any settings that are required by the extension to the `analyze-settings.properties` file.
3.     Add any resources that are required by the extension to the `/configs/<config_name>/configuration` directory. For example, the `group-based-default-security-dimension-values.xml` file.

I'm not sure what you did with the `pre-reqs/templates` files, but if you follow the above steps and provide the name of the class for the AuditLogger in the `analyze-settings.properties` file does that work for you? Additionally, if you put the `CSVAudit.properties` file in the `configuration` directory.

We do have an item on our backlog to combine the two repositories together into analyze-containers to provide a single experience, however I do not know when this is likely to happen.

Thanks,
Matt

**Comment by bohdanszymanik** [comment]
I'm pretty sure I did try that and it didn't work. But to be sure, I'll try it again with a clean deployment.

**Comment by bohdanszymanik** [comment]
OK - my bad. I've double triple tried and having AuditLogger set in analyze-settings.properties is the correct place to get it working. I must've updated that then forgotten I'd done it and moved onto trying that ApolloServerSettingsMandatory.properties file.

It will be much simpler to follow if you do managed to merge the two repositories together.
