### ISSUE TITLE
tar: Error is not recoverable: exiting now

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#2]
vscode ➜ /home/sdor/analyze-containers-252/scripts $ create-dev-environment

#----------------------------------------------------------------------
# Running create-environment script
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# Setting up i2 Analyze Minimal Toolkit
#----------------------------------------------------------------------
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
vscode ➜ /home/sdor/analyze-containers-252/scripts $ 

I received the error above. I had a working environment running in Docker. I followed this steps, https://i2group.github.io/analyze-containers/content/managing_upgrade_env.html to upgrade from 2.5.0 to 2.5.2. But got stuck on point 5 when I tried to run the script to create a dev environment. I had the latest version already of the i2 Analyze and copied the files from my working environment.

![image](https://user-images.githubusercontent.com/52672945/234487191-36486971-d2c8-4096-8072-baa810f50dbc.png)

**Comment by Anthony-Johnson-i2** [comment]
Hi Steven

I will have a chat with our team and I or they will get back to you on this.

Cheers

**Comment by Kirk-Fitzsimons-i2** [comment]
Hi Steven,

Thank you for raising the issue, similar to the other [issue ](https://github.com/i2group/analyze-containers/issues/3) raised can I ask that you please use the "Issue: Bug report" template provided when raising issues, it will help us to evaluate and debug the issue easier.

Can I ask that you provide a screenshot of your /home/sdor/analyze-containers-252/pre-reqs directory please.

Kirk

**Comment by sdorresteijn88** [comment]
Morning Kirk,

I'll use the template next time. Attached the screenshot.

![image](https://user-images.githubusercontent.com/52672945/235413800-7f6ffd24-ef23-4662-a127-55f8070b7bb6.png)

**Comment by Anthony-Johnson-i2** [comment]
Hi @Kirk-Fitzsimons-i2 just pinging you in case you did not see Steven's response.

**Comment by Anthony-Johnson-i2** [comment]
Hi 

I am sorry that it is taking so long for someone to get back to you regarding this.

I have spoken with Kirk and another member of the team a couple of times and have been assured that someone will look into this for you.

Cheers

**Comment by Anthony-Johnson-i2** [comment]
Please see the comment from Kirk on your other issue here @sdorresteijn88 .

Cheers

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  Steven
Did you need any more help with this issue or has the response from Kirk on your other issue also helped you to solve this one as well?

Cheers

**Comment by sdorresteijn88** [comment]
I think this one is solved than as well.

**Comment by Anthony-Johnson-i2** [comment]
Thanks for updating and closing.
