### ISSUE TITLE
Share record from ANBP to i2 Notebook

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#21]
Good afternoon,

I created a support case (00017132), they forwarded it to Github.

Somehow the sharing from ANBP 10 to i2 Notebook doesn’t work. From i2 Notebook to ANBP it works perfectly.
  
ANBP: 10.0.1
I2 Analyze: 4.4.3
  
1.	Add e.g. a person to the chart in ANBP
 
![image](https://github.com/i2group/analyze/assets/52672945/dcf0e20f-e03e-48bb-b34f-834d88d7a6ce)

2.	Share record
 
![image](https://github.com/i2group/analyze/assets/52672945/e6d829e2-ad9b-45a4-956f-a5b84fe14bf2)

3.	When I click on ‘copy to chart’ nothing happens (except that the target chart popup appears). When I click OK nothing happens.
 
![image](https://github.com/i2group/analyze/assets/52672945/a25aa020-91c9-427e-b8d3-c4118ab67876)

4.	Select ‘New chart’ and OK
 
![image](https://github.com/i2group/analyze/assets/52672945/2d7ad934-c638-40c4-99b1-fdf6a58e1de3)
![image](https://github.com/i2group/analyze/assets/52672945/1069da51-69a1-4085-8e1b-f73438d2e80d)

**Comment by sdorresteijn88** [comment]
@Anthony-Johnson-i2 thank you for moving the issue and for your reply.

I have ssl set up in my deployment.

There are no errors in the console as well.
![image](https://github.com/i2group/analyze-containers/assets/52672945/9b004531-bb27-46f6-86eb-197b02560cae)

![image](https://github.com/i2group/analyze-containers/assets/52672945/2b7e80e2-a9fb-4130-9e2c-dce22bd7250f)

**Comment by Ariana-Hlavaty-i2** [comment]
Hi @sdorresteijn88 can you please give us more information about your analyze-containers deployment?

- OS: [e.g. Mac, Windows]
- Version: [e.g. v2.0.0]
- Environment type: [e.g. pre-prod, config-dev]
- Deployment pattern: [e.g. istore, i2c, cstore, i2c_istore, i2c_cstore, schema_dev]

**Comment by sdorresteijn88** [comment]
@Ariana-Hlavaty-i2 sure
OS: Windows
Version: 2.8.0
Env: config-dev
Deployment pattern: i2c-istore

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  Steven


We have now also tried record sharing in a container based deployment like yours and the sharing worked for us as expected. So at this point we do not think there is a general containers specific issue with this functionality, images below:

![image](https://github.com/i2group/analyze-containers/assets/98407720/896efef3-e6f7-44cc-a3a8-fbbc5688aa25)

![image](https://github.com/i2group/analyze-containers/assets/98407720/abce38c6-f13e-4084-87f6-e9ef2f960944)

This would lead us to believe that perhaps something is different in your specific environment.

Did you resolve all of the permissions issues that you had after upgrading?

Cheers

**Comment by sdorresteijn88** [comment]
@Anthony-Johnson-i2 thank you for your reply! Good to know that is was something in my environment.

Finally I found the issue. I had a plugout running (professional service asset). After I disabled that one, it worked fine. Don't know the real issue, I have to investigate further. But for now it's working.

**Comment by Anthony-Johnson-i2** [comment]
HI @sdorresteijn88  Steven for future reference, which asset was it that was stopping/intercepting this?

**Comment by Anthony-Johnson-i2** [comment]
Ok thank you I will mention this so that folks have awareness.

Cheers
