### ISSUE TITLE
Chart store configuration

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-containers#23]
**Describe the bug**
I'm running analyze containers with DEPLOYMENT_PATTERN="i2c_cstore"

When I attempt to publish a chart I get the following error
![image](https://github.com/i2group/analyze-containers/assets/271575/fef758d5-9d9f-4904-aae1-8af2d8dd7300)

**To Reproduce**

1. Add an entity to the chart
2. Go to Publish menu
3. Click Upload Chart

**Expected behavior**
An uploaded chart.

**Hardware and Software information**
Fill in the following information:

- OS: Windows
- Analyze-Containers version: 2.8.0
- i2 Analyze version: 4.4.3
- Environment type: config-dev
- Deployment pattern: i2c_cstore

**Additional context**
I suspect I'm trying to do something wrong here but hoping for advice...

**Comment by Anthony-Johnson-i2** [comment]
Hi @bohdanszymanik 
We have an article regarding this on our support Knowledgebase 

[ I2 Analyze Chart Store – “upload failed: This chart can no longer be uploaded”. ](https://support.i2group.com/s/article/2698)    

This is part of a searchable resource that you can use.

[How can we Help you?](https://support.i2group.com/s/)
Just type part of your error message or the problem in the search bar there.

Hopefully you are seeing this for the same reason that is detailed in teh article I linked.

For future reference, as your question/problem is product related and not related to i2 Analyze containerized deployment  specifically, you would  be best to raise a support ticket by filling out the form here:

[Raise a customer support ticket](https://i2group.com/support-request) 

Cheers

**Comment by bohdanszymanik** [comment]
Thanks, just working through the security config now - I had changed the default config as provided in the analyze containers distribution. Will close.
