### ISSUE TITLE
Error installing analyze-containers 2.9.0

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-containers#24]
**Describe the bug**
I was rebuilding from scratch my analyze-containers environment using the latest version 2.9.0 release and found the errors in the log file below. I simply followed the steps in https://i2group.github.io/analyze-containers/content/getting_started.html which I'd successfully used previously for 2.6.0, 2.7.1, and 2.8.0. 

Here's the log from the terminal in vscode. There's a warning about mismatched platform architecture and then an error on installing i2analyzeMinimal.

vscode ➜ /home/bohszy/analyze-containers $ ./bootstrap -v
latest: Pulling from i2group/i2eng-analyze-containers-client
5995d2c3a044: Pull complete 
57606f358ad8: Pull complete 
215374d5e674: Pull complete 
74f097434575: Pull complete 
cc9c9f0ab3e8: Pull complete 
65e17809f01e: Pull complete 
dc5be05d50c9: Pull complete 
d67d47c37f50: Pull complete 
5dc1d88556ba: Pull complete 
32b2682217dd: Pull complete 
Digest: sha256:e076b4a9c9b1f6d700df0a339f4de6d1481f0fb75dc2bb3ab7c8fd73b74f0bcc
Status: Downloaded newer image for i2group/i2eng-analyze-containers-client:latest
docker.io/i2group/i2eng-analyze-containers-client:latest
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
Using the latest version: 2.9.0
2.9.0: Pulling from i2group/i2eng-analyze-containers-client
0765fffac8ba: Already exists 
ac79c30eef67: Already exists 
66f14141a1c6: Already exists 
7d63e9548887: Already exists 
6442c06a7606: Already exists 
fe08c5c6fa18: Pull complete 
2c2c12c8c0ce: Pull complete 
8920c0c88434: Pull complete 
0eb76e987cc3: Pull complete 
bba2663c74a6: Pull complete 
Digest: sha256:28861d9b5f201f1d1b20f46dcbd64f816d39a0b661ddcc3b51063052f25f6d01
Status: Downloaded newer image for i2group/i2eng-analyze-containers-client:2.9.0
docker.io/i2group/i2eng-analyze-containers-client:2.9.0
Downloading sqlserver JDBC driver version 12.6.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1435k  100 1435k    0     0   932k      0  0:00:01  0:00:01 --:--:-- 11.6M
sqlserver JDBC driver downloaded successfully.
Downloading postgres JDBC driver version 42.7.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1063k  100 1063k    0     0   602k      0  0:00:01  0:00:01 --:--:--  602k
postgres JDBC driver downloaded successfully.

#----------------------------------------------------------------------
# Installing config-dev environment
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# Running create-environment script
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# Setting up i2 Analyze Minimal Toolkit
#----------------------------------------------------------------------
tar (child): /opt/analyze-containers/pre-reqs/i2analyzeMinimal.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Also, notice here's the created Docker images - notice the mismatched architecture again.
![image](https://github.com/i2group/analyze-containers/assets/271575/e88ba325-9b7a-4e51-a89f-bce7d0137845)

**To Reproduce**
Simply follow the instructions in [https://i2group.github.io/analyze-containers/content/getting_started.html](https://i2group.github.io/analyze-containers/content/getting_started.html)

**Expected behavior**
Successful install

**Hardware and Software information**
Fill in the following information:

- OS: Windows
- Version: 2.9.0
- i2 Analyze version: i2analyzeMinimal-4.4.3.0-GM.tar.gz renamed to i2analyzeMinimal.tar.gz as per instructions

I'm running on a Windows 11 pro laptop, Core i5-8250U. Version info from vscode:
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22635

**Comment by Matt-Hadfield-i2** [comment]
Hi @bohdanszymanik ,

Sorry that you are hitting an issue with your installation.

It sounds like the error is because the system doesn't have the correct permissions to access the `i2analyzeMinimal.tar.gz`. Have you tried deleting it and copying it again from the system where you downloaded it?

Thanks,
Matt

**Comment by bohdanszymanik** [comment]
Hmm - the i2analyzeMinimal.tar.gz file is in the pre-reqs directory and I've done a chmod o+wx on it. I can interactively tar -tvf from within the vscode terminal, but it fails on running ./bootstrap when trying to read /opt/analyze-containers/pre-reqs/i2analyzeMinimal.tar.gz.

Is it trying to run on the vsc-analyze-containers container? If it is, then I don't see that file there?
![image](https://github.com/i2group/analyze-containers/assets/271575/b67fe44b-d8c2-4419-b424-95a47cef6581)

**Comment by bohdanszymanik** [comment]
OK, I realise I was doing a step differently in the instructions - now I still get an error but it's different. I was using the WSL terminal to start up vscode in the analyze-containers directory with 'code'. This time I followed the instructions and from within vscode I went 
WSL: Connect to WSL
Dev Containers: Open Folder in Container...
Selected the analyze-containers directory and this time I get this error:
![image](https://github.com/i2group/analyze-containers/assets/271575/907be18a-e13e-4709-bb39-e54fff41e9a2)

I'll try uninstalling vscode and reinstalling.

**Comment by bohdanszymanik** [comment]
Hmmm - exactly the same problem with 2.9.1. My Docker Desktop is version 4.28.0 (139021). In the meantime I'm going to try going back to some of the earlier analyze-containers releases to see if they work.

**Comment by Matt-Hadfield-i2** [comment]
Hi @bohdanszymanik , can you try with version 4.27.2 (137060) of Docker Desktop.

We did see an issue with 4.28 so it might be this that you're hitting.

Thanks,
Matt

**Comment by bohdanszymanik** [comment]
Ah - that seems to be it. I've run the same process through on a different device with an older version of Docker Desktop but with version 2.9.1 of analyze-containers and yes, it runs ok.

Now - the trick is... how do we download earlier versions of docker desktop :) I'll see what I can find.

**Comment by Matt-Hadfield-i2** [comment]
@bohdanszymanik you can download it from here: https://docs.docker.com/desktop/release-notes/#4272

Glad you managed to get it working.

Thanks,
Matt
