### ISSUE TITLE
Logging of security failures

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-containers#26]
### Background on the problem the feature will solve/improved user experience
When creating a security configuration eg by modifying the default security-schema/command-access-control/user.registry xml files, it's difficult to understand why access is sometimes allowed versus not allowed.

It would be useful to have some logging facility in the analyze-containers server that could be turned on to give more explanation of why access is granted or not granted.

**Comment by bohdanszymanik** [comment]
OK, I've noticed that i2 Analyze supports log4j logging through the config/server.json file where you can do like the following:
{....
},
"log": {
...
}
Using this we can see authorisation failures in the log eg
WARN ... com.i2group.disco.catalogservice.internal.CatalogResourceDelegate - com.i2group.disco.common.exception.ForbiddenAccessException: The user has no access levels associated with any of the values in the following dimensions: [...]

The question I have is how do we configure the same logging in Analyze-Containers?

**Comment by bohdanszymanik** [comment]
Great - that's what I needed. Got my logging going now.

**Comment by Anthony-Johnson-i2** [comment]
Excellent news, thanks for letting us know.
