### ISSUE TITLE
Unable to install solr_client_redhat:4.4.3.0

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-containers#29]
**Describe the bug**
Running a fresh analyze-containers install and getting the following error message:
#----------------------------------------------------------------------
# Configuring ZooKeeper cluster for Solr
#----------------------------------------------------------------------
Unable to find image 'solr_client_redhat:4.4.3.0' locally
docker: Error response from daemon: pull access denied for solr_client_redhat, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**To Reproduce**

1. Follow the instructions in https://i2group.github.io/analyze-containers/content/deploy_config_dev.html
2. (Note that I set deployment pattern to i2c_cstore - I'll try something simpler like schema_dev and see how that goes and update)
3. Execute deploy -c <your config-development directory name here>

**Expected behavior**
It downloads and installs the redhat solr image

**Hardware and Software information**

- OS: Windows
- Version: v2.9.3
- i2 Analyze version: 4.4.3
- Environment type: config-dev
- Deployment pattern: i2c_cstore
- Docker Desktop v4.32.0

**Comment by Matt-Hadfield-i2** [comment]
Hi @bohdanszymanik ,

It looks like that image might have been removed from your system. If you run `create-dev-environment` it will redownload the image and you should be able to run the `deploy` command again.

Thanks,
Matt

**Comment by bohdanszymanik** [comment]
It mentioned create-dev-environment so I gave it a go and yes, seemed to
fix it. Didn't get round to updating here till after your answer. Thanks!

Ps what kicked this off was rebuilding the dev environment which I was
doing because docker desktop was coming up with an error about being unable
to connect to wsl. All very odd and seems to be working fine now after
reinstalling.

**Comment by Anthony-Johnson-i2** [comment]
@bohdanszymanik  Glad this is now working for you, I'll close this issue. 

Cheers
