### ISSUE TITLE
Rebuild of the plugin doesn't work

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#4]
**Describe the bug**
I made some small changes to a React plugin but the plugin doesn't update. See https://github.com/i2group/notebook-sdk/issues/5 for more details.

**To Reproduce**
1. Create a React plugin
2. Add this the your config
3. Deploy your config
4. Change your plugin and create a new build
5. Deploy your config again.

**Expected behavior**
See https://github.com/i2group/notebook-sdk/issues/5

**Screenshots**
See https://github.com/i2group/notebook-sdk/issues/5

**Hardware and Software information**
Fill in the following information:

- OS: Windows with Chrome v116.0.x
- Analyze container version: 2.7.0
- i2 Analyze version: 4.2.2
- Environment type: config-dev
- Deployment pattern: i2c

**Comment by Oleksandr-Kushchak-i2** [comment]
Hi, I can see there is a resonable suggestion in the [linked issue comment](https://github.com/i2group/notebook-sdk/issues/5#issuecomment-1718913654).
As a workaround you can delete `i2a-plugins/.i2a-plugins/{plugin_name}.sha512` file and redeploy your configuration. This will ensure that the plugin is rebuilt. If you still don't see your change - the new file didn't make it to the `i2a-plugins/{plugin_name}` directory and hence is not updated.
