### ISSUE TITLE
Permission error for new version of a plugin

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#5]
**Describe the bug**
I created a new version of 2 plugins (car-registration and anpr). Locally it worked fine but on our demo environment I got a lot of permission errors.

#----------------------------------------------------------------------

Building connectors
#----------------------------------------------------------------------
tar: dist/schema-charting-schemes.xml.bak: Cannot open: File exists
tar: dist/schema.xml.bak: Cannot open: File exists
tar: dist/data-service.js: Cannot open: File exists
tar: dist/index.js: Cannot open: File exists
tar: dist/schema/law-enforcement-schema.js: Cannot open: Permission denied
tar: dist/result-building.js: Cannot open: File exists
tar: dist/schema.js: Cannot open: File exists
tar: dist/data/account_organisation.json: Cannot open: Permission denied
tar: dist/data/account_person.json: Cannot open: Permission denied
tar: dist/data/address - Copy.json: Cannot open: Permission denied
tar: dist/data/address.json: Cannot open: Permission denied
tar: dist/data/cars.json: Cannot open: Permission denied
tar: package.json: Cannot open: File exists
tar: dist/data/persons_addresses.json: Cannot open: Permission denied
tar: dist/data/persons_cars.json: Cannot open: Permission denied
tar: dist/data/persons.json: Cannot open: Permission denied
tar: config/server.json: Cannot open: File exists
tar: config/settings.json: Cannot open: File exists
tar: dist/data/transaction_link.json: Cannot open: Permission denied
tar: dist/data-service.js.map: Cannot open: File exists
tar: dist/index.js.map: Cannot open: File exists
tar: dist/schema/law-enforcement-schema.js.map: Cannot open: Permission denied
tar: dist/result-building.js.map: Cannot open: File exists
tar: dist/schema.js.map: Cannot open: File exists
tar: README.md: Cannot open: File exists
tar: .env.sample: Cannot open: File exists
tar: dist/schema/law-enforcement-schema-charting-schemes.xml: Cannot open: Permission denied
tar: dist/schema/law-enforcement-schema.xml: Cannot open: Permission denied
tar: dist/schema-charting-schemes.xml: Cannot open: File exists
tar: dist/schema.xml: Cannot open: File exists
tar: Exiting with failure status due to previous errors
vscode ➜ /analyze-containers-270 $ sudo deploy -c config-demo
sudo: deploy: command not found
vscode ➜ /analyze-containers-270 $

**To Reproduce**
Delete the old tgz file and add the new tgz file in the connector folder
Update the connector-version.json
Run 'deploy -c demo-config'

**Expected behavior**
I expect that the new connector is unpacked and installed correctly.

**Screenshots**
None

**Hardware and Software information**
Local: Ubuntu 22.04.2 LTS, i2 Analyze 4.4.2, analyze-containers 2.6.0
Demo environment: Ubuntu 22.10, i2 Analyze 4.4.2, analyze-containers 2

**Additional context**
This morning I changed the .devcontainer/devcontainer.json and commented out the remoteUser. I had hoped that this would solve the permission errors, but than I get the message that the command is not found.

root ➜ /analyze-containers-270 $ deploy -c config-demo
bash: deploy: command not found

**Comment by Matt-Hadfield-i2** [comment]
Hi [sdorresteijn88](https://github.com/sdorresteijn88),

Which version of analyze-containers are you using? It looks like the demo environment is running on 2.7.0 and the local on 2.6.0.

You shouldn't ever need to modify the devcontainer.json file - the way that permissions are designed and implemented should work and if not we can investigate and ensure the dev container is configured correctly.

Are the permissions in the new connectors the same as the previous ones? If you do an `ls -l` on the dist folder what are the permissions and owner of those files?

Hopefully this info can help us diagnose the issue.

**Comment by sdorresteijn88** [comment]
Hi Matt,

Thanks for your response!

The problem occurs in the 2.7.0 version indeed. For now I focus only on the ANPR connector.

This is the ANPR connector (updated and not working)
![image](https://github.com/i2group/analyze-containers/assets/52672945/6a05af76-bf36-48b9-ac6d-8195627fc4b2)

This is another connector (not changed and still working)
![image](https://github.com/i2group/analyze-containers/assets/52672945/e56d81f1-7bf6-4338-b36e-68eb11ab215f)

**Comment by sdorresteijn88** [comment]
I tried to add a new created connector and get also a permission error on the demo environment (2.7.0) while it worked perfect locally (2.6.0).

Below the docker versions, because they are also not exactly the same.
Local: Docker version 24.0.5, build ced0996
Demo environment: Docker version 24.0.6, build ed223bc

This is the error for the new connector, after running 'deploy -c {{my config}}'.
#----------------------------------------------------------------------
# Building connectors
#----------------------------------------------------------------------
mkdir: cannot create directory ‘/analyze-containers-270/connector-images/crypto-connector/.app’: Permission denied
vscode ➜ /analyze-containers-270/connector-images/crypto-connector $ ls -l
total 24
drwxr-xr-x 2 root root 4096 Oct  4 18:59 app
-rw-r--r-- 1 root root  249 Oct  4 18:07 connector-definition.json
-rw-r--r-- 1 root root   42 Oct  4 18:07 connector-version.json
-rw-r--r-- 1 root root 6340 Oct  4 18:49 crypto-connector-0.1.0.tgz
-rw-r--r-- 1 root root 1125 Oct  4 18:07 Dockerfile
vscode ➜ /analyze-containers-270/connector-images/crypto-connector $

**Comment by sdorresteijn88** [comment]
Hi @Matt-Hadfield-i2 , I forgot to mention you. So maybe you're not aware of my response.

**Comment by Matt-Hadfield-i2** [comment]
Hey @sdorresteijn88 - thanks for your replies.

I passed onto the team and it could be an issue with the file permissions.

Can you try updating the ownership of the app folder to `vscode vscode` in the connectors that are not working? (To match the holehe connector)

Thanks,

**Comment by sdorresteijn88** [comment]
Hi @Matt-Hadfield-i2 

I tried it, but the user vscode was 

```
chown: invalid user: ‘vscode:vscode’
chown vscode:vscode app
```
So I added to vscode user.

![image](https://github.com/i2group/analyze-containers/assets/52672945/6c7f927b-dcfb-490a-a20e-c3a2985e566e)

After this I deployed the config again and got this error.
```
#----------------------------------------------------------------------
# Building connectors
#----------------------------------------------------------------------
mkdir: cannot create directory ‘/analyze-containers-270/connector-images/crypto-connector/.app’: Permission denied
```

I created it manual, but than I get the error that the .app folder can't be deleted.

Do you have any suggestions to fix this?

**Comment by sdorresteijn88** [comment]
Hi @Matt-Hadfield-i2,

Thanks a lot for your help this morning! Below a short recap.

A colleague did set up the i2 Analyze server. I added my SSH key, but didn't create a user in Ubuntu. I should have add a user for myself as well in the same group as my colleague. 

The workaround was running the command below in the connector-images folder.

```
chown -R 1000:1000 .
```
