### ISSUE TITLE
i2 Analyze in Docker container in air gab network

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#8]
Good morning,

Are there some best practices to set up the i2 Analyze in Docker in an air gab network? Is there also a list of the required dependencies?

best regards,
Steven

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  (Steven) I had a chat with dev on this for you and this will most likely give you what you need to know.

[External Dependencies](https://i2group.github.io/analyze-containers/versions/2.7.0/content/reference%20architecture/external_dependencies.html?q=external)

For some reason that doesn't exist on latest so we will get that rectified.

Cheers

**Comment by sdorresteijn88** [comment]
@Anthony-Johnson-i2 thanks a lot!
