### ISSUE TITLE
ERROR: i2 Analyze Minimal Toolkit version 4.4.3.0 is not compatible with analyze-containers version 2.7.1

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#9]
**Describe the bug**
I received the product update that a new version of the Toolkit is available and tried to install it locally.

**To Reproduce**
1. Download version 4.4.3 of the Minimal Toolkit
2. Put the file in the /pre-reqs folder
3. Open the container in VSCode
4. After the Dev Container is ready run the command 'create-dev-environment'

When can we expect the new release for the i2 Analyze Containers (https://github.com/i2group/analyze-containers/releases)?
```
This application is configured for access on https://i2analyze.eia:9443/opal
vscode ➜ /home/sdor/analyze-containers-271 $ create-dev-environment

#----------------------------------------------------------------------
# Running create-environment script
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# Setting up i2 Analyze Minimal Toolkit
#----------------------------------------------------------------------

ERROR: i2 Analyze Minimal Toolkit version 4.4.3.0 is not compatible with analyze-containers version 2.7.1
vscode ➜ /home/sdor/analyze-containers-271 $ 
```

**Comment by Matt-Hadfield-i2** [comment]
Hi @sdorresteijn88 ,

You have followed the right process however we have not released the next version of analyze-containers that provides support for 4.4.3.

We are currently working towards the release but it will not be available this month.

Thank you for showing interest in the platform.
